on:
  pull_request:
    branches:
      - develop

jobs:
  
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: npm ci 
      - run: npm run build

  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run test

  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run lint



