on:
  pull_request:

jobs:
  
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: npm ci 
      - run: npm run build

  test:
    runs-on: ubuntu-20.04
    steps:
      - run: echo test Works!



