name: Continuous Deployment

on:
  push:
    branches: [main]

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/default.yml
    secrets: inherit
    permissions: write-all

  dev:
    name: Deploy
    runs-on: ubuntu-20.04
    needs: [ci]
    steps:
      - run: echo Works!
