name: Continuous Deployment

on:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - uses: ./.github/workflows/default.yml

  dev:
    name: Deploy
    runs-on: ubuntu-20.04
    needs: [ci]
    steps:
      - run: echo Works!
