name: Continuous Deployment

on:
  push:
    branches: [main]

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/default.yml
    secrets: inherit
    permissions: write-all

  dev:
    name: Staging Deploy
    runs-on: ubuntu-20.04
    needs: [ci]
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-16
          path: build

      - name: Publish to netlify
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=build --alias=staging --message "Deploy from Github Action"
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
